const emerald = "#1B6B4A";
const deepGreen = "#0F3D2B";
const forestGreen = "#14523A";
const richGold = "#D4A843";
const darkGold = "#B8922E";
const lightGold = "#F0DDA0";
const warmCream = "#FAF8F5";
const ivory = "#F5F2ED";

export default {
  light: {
    text: "#1A1A1A",
    textSecondary: "#6B7280",
    textTertiary: "#9CA3AF",
    background: warmCream,
    surface: "#FFFFFF",
    surfaceElevated: "#FFFFFF",
    surfaceSecondary: ivory,
    tint: emerald,
    accent: richGold,
    accentMuted: lightGold,
    tabIconDefault: "#9CA3AF",
    tabIconSelected: emerald,
    border: "#E8E5E0",
    borderLight: "#F0EDE8",
    card: "#FFFFFF",
    cardShadow: "rgba(15, 61, 43, 0.06)",
    emerald,
    deepGreen,
    forestGreen,
    gold: richGold,
    goldLight: "#F7EED4",
    gradientStart: "#1B6B4A",
    gradientEnd: "#0A2E1E",
    gradientMid: forestGreen,
    prayerActiveBg: emerald,
    prayerActiveText: "#FFFFFF",
    prayerIconBg: "#EDF5F0",
    categoryBadgeBg: (hex: string) => hex + "15",
    bannerBg: "#FEF3C7",
    bannerText: "#92400E",
    actionButtonBg: "#EDF5F0",
    divider: "#F0EDE8",
    tickerBg: "#FFF8E7",
    tickerUrgentBg: "#FEF2F2",
    tickerText: "#92400E",
    tickerUrgentText: "#991B1B",
    heroOverlay: "rgba(15, 61, 43, 0.03)",
    sectionDivider: "#F0EDE8",
  },
  dark: {
    text: "#F5F5F5",
    textSecondary: "#9CA3AF",
    textTertiary: "#6B7280",
    background: "#0C0C0C",
    surface: "#161616",
    surfaceElevated: "#1E1E1E",
    surfaceSecondary: "#1A1A1A",
    tint: richGold,
    accent: richGold,
    accentMuted: "#3D3323",
    tabIconDefault: "#6B7280",
    tabIconSelected: richGold,
    border: "#252525",
    borderLight: "#1E1E1E",
    card: "#161616",
    cardShadow: "rgba(0, 0, 0, 0.3)",
    emerald,
    deepGreen,
    forestGreen,
    gold: richGold,
    goldLight: "#2A2318",
    gradientStart: "#1A4A35",
    gradientEnd: "#0C2A1C",
    gradientMid: "#143D2E",
    prayerActiveBg: richGold,
    prayerActiveText: "#0C0C0C",
    prayerIconBg: "#1A2E22",
    categoryBadgeBg: (hex: string) => hex + "25",
    bannerBg: "#3D3323",
    bannerText: "#D4A843",
    actionButtonBg: "#1A2E22",
    divider: "#1E1E1E",
    tickerBg: "#2A2318",
    tickerUrgentBg: "#2A1818",
    tickerText: "#D4A843",
    tickerUrgentText: "#F87171",
    heroOverlay: "rgba(212, 168, 67, 0.03)",
    sectionDivider: "#1E1E1E",
  },
};
