const emerald = "#1B6B4A";
const deepGreen = "#0F3D2B";
const forestGreen = "#14523A";
const richGold = "#D4A843";
const darkGold = "#B8922E";
const lightGold = "#F0DDA0";
const warmCream = "#FAF8F5";
const ivory = "#F5F2ED";

const ramadanPurple = "#6B3FA0";
const deepPurple = "#3D2066";
const plumPurple = "#4E2D78";

const baseLight = {
  text: "#1A1A1A",
  textSecondary: "#6B7280",
  textTertiary: "#9CA3AF",
  background: warmCream,
  surface: "#FFFFFF",
  surfaceElevated: "#FFFFFF",
  surfaceSecondary: ivory,
  accent: richGold,
  accentMuted: lightGold,
  tabIconDefault: "#9CA3AF",
  border: "#E8E5E0",
  borderLight: "#F0EDE8",
  card: "#FFFFFF",
  cardShadow: "rgba(15, 61, 43, 0.06)",
  gold: richGold,
  goldLight: "#F7EED4",
  prayerActiveText: "#FFFFFF",
  categoryBadgeBg: (hex: string) => hex + "15",
  bannerBg: "#FEF3C7",
  bannerText: "#92400E",
  divider: "#F0EDE8",
  tickerBg: "#FFF8E7",
  tickerUrgentBg: "#FEF2F2",
  tickerText: "#92400E",
  tickerUrgentText: "#991B1B",
  sectionDivider: "#F0EDE8",
};

const baseDark = {
  text: "#F5F5F5",
  textSecondary: "#9CA3AF",
  textTertiary: "#6B7280",
  background: "#0C0C0C",
  surface: "#161616",
  surfaceElevated: "#1E1E1E",
  surfaceSecondary: "#1A1A1A",
  accent: richGold,
  accentMuted: "#3D3323",
  tabIconDefault: "#6B7280",
  border: "#252525",
  borderLight: "#1E1E1E",
  card: "#161616",
  cardShadow: "rgba(0, 0, 0, 0.3)",
  gold: richGold,
  goldLight: "#2A2318",
  prayerActiveText: "#0C0C0C",
  categoryBadgeBg: (hex: string) => hex + "25",
  bannerBg: "#3D3323",
  bannerText: "#D4A843",
  divider: "#1E1E1E",
  tickerBg: "#2A2318",
  tickerUrgentBg: "#2A1818",
  tickerText: "#D4A843",
  tickerUrgentText: "#F87171",
  sectionDivider: "#1E1E1E",
};

export default {
  light: {
    ...baseLight,
    tint: emerald,
    tabIconSelected: emerald,
    emerald,
    deepGreen,
    forestGreen,
    gradientStart: "#1B6B4A",
    gradientEnd: "#0A2E1E",
    gradientMid: forestGreen,
    prayerActiveBg: emerald,
    prayerIconBg: "#EDF5F0",
    actionButtonBg: "#EDF5F0",
    heroOverlay: "rgba(15, 61, 43, 0.03)",
  },
  dark: {
    ...baseDark,
    tint: richGold,
    tabIconSelected: richGold,
    emerald,
    deepGreen,
    forestGreen,
    gradientStart: "#1A4A35",
    gradientEnd: "#0C2A1C",
    gradientMid: "#143D2E",
    prayerActiveBg: richGold,
    prayerIconBg: "#1A2E22",
    actionButtonBg: "#1A2E22",
    heroOverlay: "rgba(212, 168, 67, 0.03)",
  },
  lightRamadan: {
    ...baseLight,
    tint: ramadanPurple,
    tabIconSelected: ramadanPurple,
    emerald: ramadanPurple,
    deepGreen: deepPurple,
    forestGreen: plumPurple,
    gradientStart: "#6B3FA0",
    gradientEnd: "#2E1A4E",
    gradientMid: plumPurple,
    prayerActiveBg: ramadanPurple,
    prayerIconBg: "#F0EBF5",
    actionButtonBg: "#F0EBF5",
    heroOverlay: "rgba(107, 63, 160, 0.03)",
  },
  darkRamadan: {
    ...baseDark,
    tint: richGold,
    tabIconSelected: richGold,
    emerald: ramadanPurple,
    deepGreen: deepPurple,
    forestGreen: plumPurple,
    gradientStart: "#3D2066",
    gradientEnd: "#1A0E33",
    gradientMid: "#2E1850",
    prayerActiveBg: richGold,
    prayerIconBg: "#1E1533",
    actionButtonBg: "#1E1533",
    heroOverlay: "rgba(212, 168, 67, 0.03)",
  },
};
